import React, { useState, useEffect } from 'react';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import Header from '../components/Header';
import ExecutionSteps from '../components/ExecutionSteps';
import { FileExplorer } from '../components/FileExplorer';
import CodePreview from '../components/CodePreview';
import Button from '../components/ui/Button';
import { ExecutionStep, FileItem } from '../types';
import axios from 'axios';

const ResultsPage: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('');
  const [steps, setSteps] = useState<ExecutionStep[]>([]);
  const [fileItems, setFileItems] = useState<FileItem[]>([]);
  const [selectedFile, setSelectedFile] = useState<FileItem | null>(null);
  const [currentStepId, setCurrentStepId] = useState<string | undefined>();
  const [isGenerating, setIsGenerating] = useState(true);
  
  // Add this line to initialize with mock files immediately
  useEffect(() => {
    setFileItems(mockFiles);
  }, []);
  
  const mockFiles: FileItem[] = [
    {
      name: 'index.html',
      path: 'src/index.html', // Remove leading slash
      content: '<!DOCTYPE html><html><head><title>My Website</title></head><body><h1>Hello, world!</h1></body></html>',
      type: 'file' as const
    },
    {
      name: 'styles.css',
      path: 'src/css/styles.css', // Remove leading slash
      content: 'body { background-color: #f0f0f0; }',
      type: 'file' as const
    },
    {
      name: 'script.js',
      path: 'src/js/script.js', // Remove leading slash
      content: 'console.log(\'Hello from JavaScript!\');',
      type: 'file' as const
    },
    {
      name: 'app.js',
      path: 'src/js/app.js', // Remove leading slash
      content: 'document.addEventListener(\'DOMContentLoaded\', () => {\n  console.log(\'App initialized\');\n});',
      type: 'file' as const
    },
    {
      name: 'reset.css',
      path: 'src/css/reset.css', // Remove leading slash
      content: '* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}',
      type: 'file' as const
    },
    {
      name: 'README.md',
      path: 'README.md', // Remove leading slash
      content: '# Project\n\nThis is a sample project generated by WebCraft.',
      type: 'file' as const
    }
  ];


  const ApiCall = async () => {
    try {
      const savedPrompt = localStorage.getItem('currentPrompt');
      if (savedPrompt) {
        const response = await axios.post('http://localhost:3000/chat', {
          messages: [{ role: 'user', content: savedPrompt }]
        });
        setPrompt(savedPrompt);
        // You can handle the API response here if needed
        console.log(response.data);
      }
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };

  useEffect(() => {
    // Enable dark mode
    document.documentElement.classList.add('dark');

    // Retrieve the prompt from local storage
    const savedPrompt = localStorage.getItem('currentPrompt');
    if (savedPrompt) {
      setPrompt(savedPrompt);
    }

        // Call the API
        ApiCall();
    
    
  }, []);

  return (
    <div className="min-h-screen bg-gray-900 flex flex-col">
      <Header />
      
      <main className="flex-grow pt-24 pb-12 px-4 container mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center">
            <Link to="/" className="text-gray-400 hover:text-blue-400 mr-4">
              <ArrowLeft className="h-5 w-5" />
            </Link>
            <h1 className="text-2xl font-bold text-white">Building Your Website</h1>
          </div>
          
          <div className="flex items-center">
            <Button 
              variant="outline" 
              className="mr-3"
              disabled={isGenerating}
              icon={<ExternalLink className="h-4 w-4" />}
            >
              Preview Site
            </Button>
            
            <Button 
              disabled={isGenerating}
            >
              Download Code
            </Button>
          </div>
        </div>
        
        {prompt && (
          <div className="bg-gray-800 border border-gray-700 rounded-lg p-4 mb-8 shadow-sm">
            <h2 className="text-sm font-medium text-gray-400 mb-2">Your Prompt</h2>
            <p className="text-gray-200">{prompt}</p>
          </div>
        )}
        
        <div className="flex flex-row gap-4 h-[calc(100vh-300px)]">
          {/* ExecutionSteps - 25% width */}
          <div className="w-1/4">
            <ExecutionSteps steps={steps} currentStepId={currentStepId} />
          </div>
          
          {/* FileExplorer - 25% width */}
          <div className="w-1/4">
            <FileExplorer 
              files={fileItems} 
              onFileSelect={(fileItem) => setSelectedFile(fileItem)} 
            />
          </div>
          
          {/* CodePreview - 50% width */}
          <div className="w-1/2">
            <CodePreview file={selectedFile} />
          </div>
        </div>
      </main>
    </div>
  );
};

export default ResultsPage;